### PR TITLE
Gracefully handle devices that do not support A/V info.

### PR DESCRIPTION
**Pull request by klaashoekstra94**
## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New integration (thank you!)
- [ ] New feature (which adds functionality to an existing integration)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example entry for `configuration.yaml`:

```yaml
# Example configuration.yaml
media_player:
  - platform: onkyo
    host: 10.10.10.10
    name: Amplifier
```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue: #46130
- Link to documentation pull request: 

## Checklist

- [ ] The code change is tested and works locally.
- [x] Local tests pass. **Your PR cannot be merged unless tests pass**
- [x] There is no commented out code in this PR.
- [x] I have followed the [development checklist][dev-checklist]
- [x] The code has been formatted using Black (`black --fast homeassistant tests`)
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

If the code communicates with devices, web services, or third-party tools:

- [ ] The [manifest file][manifest-docs] has all fields filled out correctly.  
      Updated and included derived files by running: `python3 -m script.hassfest`.
- [ ] New or updated dependencies have been added to `requirements_all.txt`.  
      Updated by running `python3 -m script.gen_requirements_all`.
- [ ] Untested files have been added to `.coveragerc`.

The integration reached or maintains the following [Integration Quality Scale][quality-scale]:

- [ ] No score or internal
- [ ] 🥈 Silver
- [ ] 🥇 Gold
- [ ] 🏆 Platinum

[dev-checklist]: https://developers.home-assistant.io/docs/en/development_checklist.html
[manifest-docs]: https://developers.home-assistant.io/docs/en/creating_integration_manifest.html
[quality-scale]: https://developers.home-assistant.io/docs/en/next/integration_quality_scale_index.html
[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by klaashoekstra94** [comment]
@OnFreund I think this will fix the issue regarding the queries for audio and video info. However I cannot test it here because my devices don't give the errors. Do you know who can test this?

**Comment by OnFreund** [comment]
Maybe @danieljkemp can help?

**Comment by especially-relative** [comment]
I was able to test it! All it took was a k8s ConfigMap, and a `lifecycle.postStart.exec.command` entry.

Anyhow, I was able to load it in HA without any errors, and all of my expected controls are working.

**Comment by klaashoekstra94** [comment]
Perfect, then we can merge this into the main PR! 🙂

**Pull request merged**
